trigger:
  - master

stages:
  - stage: checks
    displayName: Static checks
    jobs:
      - template: .ci/templates/docker-jobs.yml
        parameters:
          jobs:
            - job: lint
              displayName: Run ESLint
              steps:
                - script: yarn install && yarn run lint
            - job: types
              displayName: Run Typing Checks
              steps:
                - script: yarn install && yarn run types
            - job: audit
              displayName: Run Yarn Audit
              continueOnError: true
              steps:
                - script: yarn install && yarn audit --groups dependencies
  - stage: tests
    displayName: Run tests
    jobs:
      - template: .ci/templates/docker-jobs.yml
        parameters:
          jobs:
            - job: test
              displayName: Run test
              steps:
                - script: yarn install && yarn run test --coverage
                - script: yarn add --dev codecov && yarn run codecov
                  env:
                    CODECOV_TOKEN: $(codecov.token)
  - stage: build
    displayName: Build Project
    jobs:
      - template: .ci/templates/docker-jobs.yml
        parameters:
          jobs:
            - job: build
              displayName: Build
              steps:
              - script: yarn install && yarn run build
              - task: PublishPipelineArtifact@0
                inputs:
                  targetPath: lib/
                  artifactName: babel-plugin-i18next-extract
  